### PR TITLE
Add webpack config syntax to readme

### PR DESCRIPTION
**Pull request by timwis**
Every time I start a new project I forget how to do this, end up on this repo, and wish this example was here :P Figured I'd just add it this time.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Sorry for the delay for this.

**Comment by timwis** [comment]
I'm sorry, I'm not sure what you mean?

**Comment by SpaceK33z** [comment]
@timwis, @TheLarkInn means to explain it using the same code example as is used on that link.

**Comment by michael-ciniawsky** [comment]
This was fixed by the common README template update. Thx nevertheless 😛

**Pull request closed without merging**
