### PR TITLE
Fix Maintainer section look

### PR DESCRIPTION
**Pull request by montogeek**
**What kind of change does this PR introduce?**
Fix Maintainer section HTML

**Did you add tests for your changes?**
No

**If relevant, did you update the README?**
Yes

**Summary**

Maintainers section HTML was incorrect, making the website look like this:
image

After the change it looks like this:
image

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
Can you please close and reopen the PR to trigger the CLA Bot and resolve merge conflicts?

**Comment by michael-ciniawsky** [comment]
? 🙃

**Comment by montogeek** [comment]
@michael-ciniawsky I had to sign it again, now it works :)

**Comment by michael-ciniawsky** [comment]
@montogeek kk, thought the CLA Bot of doom messed up again :D. Thx

**Comment by montogeek** [comment]
Thanks to you @michael-ciniawsky

**Pull request merged**
